language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Zd7aiMu6jVWHofJmQ6JqXu7K6mfbMZSatvHq5IzKXLfzTNbeJvNTpgoyHbMWTAopih9Hy2XzLuh4IuVC95sNRKL+WZT3HHFJmQKLMj0/rhlJTif2YkuDngbU/3lExvbaRleJQgJsvakDiO/dTntdgzmoRudPqjUguZN+efuOz0A0mV/uefO9PbHhU2nc8l+HdUIIgXqPAc7NJY4Ld5bw2WT2BZS08J0pDbIZbeNpunRghgjyQK/uqqsAhBCTUboq+aK/bPs+yhhvqQQPwHHh5LEqiLAJe3xqUA2jF2mJoXRXiC2eSnxrAW2HRw5tjpRp2TGzudpzV0B/POgXMJExp8+yJfoV5z/6YNpPGvJv643jDZkEUW4nROhoaMn0reXqjRealcza9tcrzj63+34zGaD4JZfCiuW1l86ZMP8/ZMXcwFcYqAfdsMf8+ZJjcHm2R7mB+m3S51P6UZ5g6UKTTlleRJ7O/vHjXP4DPbNyU6ihQmtEDb0pFaMoSycHGaQBSw9ulrgJ9AE4Jb0EzH34kifxSkLNHtjSZYAAQ4dvOy++nRiRalSQk1QDIMstltb6yiN+eOYmaZSmgdQR8hwnmgeDYO69CExxcC5YVJx3uqoY7s9Sc4zLZNGuKxLr65QB726MHWPiTSB8Zn1GO7gmg8mZOk2roWkgymxHRP0z/ZY=
    app: scrap-chef-server
